# Generated by Django 5.2.7 on 2025-10-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='slug',
            field=models.SlugField(default='blank', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genus',
            name='slug',
            field=models.SlugField(default='blank', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='blank', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
