# Generated by Django 5.2.7 on 2025-10-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_family_slug_genus_slug_order_slug_alter_family_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['name'], name='birds_order_name_1ea354_idx'),
        ),
    ]
