# Generated by Django 5.2.7 on 2025-10-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['common_name']},
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['name'], name='birds_famil_name_2a9a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='genus',
            index=models.Index(fields=['name'], name='birds_genus_name_421e31_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['common_name'], name='birds_speci_common__1f782b_idx'),
        ),
    ]
