# Generated by Django 5.2.7 on 2025-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_alter_family_options_alter_genus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
