# Generated by Django 5.2.7 on 2025-10-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_location_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default='x', max_length=256),
            preserve_default=False,
        ),
    ]
