# Generated by Django 5.2.7 on 2025-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_location_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date'], name='birds_event_date_e16ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='birds_event_locatio_380a16_idx'),
        ),
    ]
