# Generated by Django 5.2.7 on 2025-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='x', max_length=48),
            preserve_default=False,
        ),
    ]
