# Generated by Django 5.2.7 on 2025-10-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0009_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
