# Generated by Django 5.2.7 on 2025-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0010_alter_event_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
